### ISSUE TITLE
JS Advanced - Advanced Functions - Error Handling

### ISSUE THREAD

**Issue by teodortenchev** [SoftUni-Internal/interactive-content#27]
**The example does not work as intended. It does not throw an exception. Locally or in the engine.**

To indicate that, it returns the special value `-1`.

- Throw an **exception**:

```js live
function toUppercase(string) {
  if (typeof string !== "string") {
    throw TypeError("The input provided is not a string");
  }

  return string.toUpperCase();
}
```

**Comment by stbodurov** [comment]
This is the updated example and brief explanation:

```js live
function toUppercase(string) {
  if (typeof string !== "string") {
    throw TypeError("The input provided is not a string");
  }

  return string.toUpperCase();
}

toUppercase(5);
```

The `toUppercase` function will throw a `TypeError`, because it is invoked with a number, instead of a string.

A pull request will be open after yours has been merged.

**Comment by teodortenchev** [comment]
Hi @stbodurov , no need to open a separate pull request. I will edit it in mine. Thanks for fixing this.

**Comment by stbodurov** [comment]
Thank you, remember to add the following description after the example:

The `toUppercase` function will throw a `TypeError`, because it is invoked with a **number**, instead of a string.
